"""Contract tests for the translated-class registry (FU-1 / gap-4).

Derived from the public API contract and Unity documentation — NOT from
reading the implementation. Tests verify:

  1. get_translated_class_names() directory-scan semantics
  2. serialize_scene(translated_classes=...) drops inline MonoBehaviours
     but keeps their GameObjects and engine-primitive components
  3. Back-compat: serialize_scene() with no kwarg emits every MonoBehaviour
  4. gen_coplay runner-to-source-dir derivation rule
  5. Engine-primitive components (Transform, SpriteRenderer, etc.) are NEVER
     dropped by the translated_classes filter
"""

from __future__ import annotations

import textwrap
import tempfile
from pathlib import Path

import pytest

from src.engine.core import _clear_registry, GameObject, MonoBehaviour
from src.engine.lifecycle import LifecycleManager
from src.engine.physics.physics_manager import PhysicsManager
from src.engine.rendering.renderer import SpriteRenderer
from src.engine.rendering.camera import Camera
from src.engine.audio import AudioListener

from src.exporter.scene_serializer import serialize_scene, _serialize_component
from src.translator.project_translator import get_translated_class_names


# ---------------------------------------------------------------------------
# Scene-state fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def clean_scene():
    """Reset all global engine state before and after each test."""
    _clear_registry()
    LifecycleManager._instance = None
    PhysicsManager._instance = None
    Camera._reset_main()
    AudioListener.reset()
    yield
    _clear_registry()
    LifecycleManager._instance = None
    PhysicsManager._instance = None
    Camera._reset_main()
    AudioListener.reset()


# ---------------------------------------------------------------------------
# Minimal MonoBehaviour subclasses for fixtures
# ---------------------------------------------------------------------------

class TranslatedBehaviour(MonoBehaviour):
    """Simulates a MonoBehaviour that exists in the translated Python package
    and has a corresponding .cs file generated by the translator."""
    def __init__(self):
        super().__init__()
        self.speed = 5.0


class InlineBehaviour(MonoBehaviour):
    """Simulates a MonoBehaviour defined inline in run_*.py (no .cs counterpart).
    The gap-4 contract says this must be dropped when a translated_classes
    registry is supplied."""
    def __init__(self):
        super().__init__()
        self.label = "inline"


# ---------------------------------------------------------------------------
# Contract 1: get_translated_class_names — directory-scan semantics
# ---------------------------------------------------------------------------

class TestGetTranslatedClassNames:

    def test_returns_empty_set_for_missing_directory(self):
        """Contract: missing directory must return an empty set, not raise."""
        result = get_translated_class_names("/does/not/exist/at/all")
        assert result == set()

    def test_returns_empty_set_for_empty_directory(self, tmp_path):
        """Contract: a directory with no .py files returns empty set."""
        result = get_translated_class_names(tmp_path)
        assert result == set()

    def test_ignores_init_py(self, tmp_path):
        """Contract: __init__.py must never contribute class names."""
        init = tmp_path / "__init__.py"
        init.write_text(
            textwrap.dedent("""\
                from src.engine.core import MonoBehaviour

                class InitClass(MonoBehaviour):
                    pass
            """),
            encoding="utf-8",
        )
        result = get_translated_class_names(tmp_path)
        assert "InitClass" not in result

    def test_collects_monobehaviour_subclass(self, tmp_path):
        """Contract: a class that inherits MonoBehaviour must appear in the result."""
        (tmp_path / "player.py").write_text(
            textwrap.dedent("""\
                from src.engine.core import MonoBehaviour

                class Player(MonoBehaviour):
                    pass
            """),
            encoding="utf-8",
        )
        result = get_translated_class_names(tmp_path)
        assert "Player" in result

    def test_excludes_non_monobehaviour_class(self, tmp_path):
        """Contract: plain Python classes not inheriting MonoBehaviour are excluded."""
        (tmp_path / "utils.py").write_text(
            textwrap.dedent("""\
                class HelperUtil:
                    pass
            """),
            encoding="utf-8",
        )
        result = get_translated_class_names(tmp_path)
        assert "HelperUtil" not in result

    def test_collects_multiple_classes_across_files(self, tmp_path):
        """Contract: multiple MonoBehaviour classes across different files are all collected."""
        (tmp_path / "player.py").write_text(
            textwrap.dedent("""\
                from src.engine.core import MonoBehaviour

                class Player(MonoBehaviour):
                    pass
            """),
            encoding="utf-8",
        )
        (tmp_path / "enemy.py").write_text(
            textwrap.dedent("""\
                from src.engine.core import MonoBehaviour

                class Enemy(MonoBehaviour):
                    pass
            """),
            encoding="utf-8",
        )
        result = get_translated_class_names(tmp_path)
        assert "Player" in result
        assert "Enemy" in result

    def test_only_scans_direct_children_not_subdirectories(self, tmp_path):
        """Contract: only *.py directly in directory — not recursive."""
        subdir = tmp_path / "subpkg"
        subdir.mkdir()
        (subdir / "nested.py").write_text(
            textwrap.dedent("""\
                from src.engine.core import MonoBehaviour

                class NestedClass(MonoBehaviour):
                    pass
            """),
            encoding="utf-8",
        )
        result = get_translated_class_names(tmp_path)
        assert "NestedClass" not in result

    def test_returns_set_not_list(self, tmp_path):
        """Contract: return type is set[str]."""
        result = get_translated_class_names(tmp_path)
        assert isinstance(result, set)

    def test_multiple_classes_same_file_all_collected(self, tmp_path):
        """Contract: a single file with two MonoBehaviour subclasses emits both names."""
        (tmp_path / "controllers.py").write_text(
            textwrap.dedent("""\
                from src.engine.core import MonoBehaviour

                class BallController(MonoBehaviour):
                    pass

                class PaddleController(MonoBehaviour):
                    pass
            """),
            encoding="utf-8",
        )
        result = get_translated_class_names(tmp_path)
        assert "BallController" in result
        assert "PaddleController" in result


# ---------------------------------------------------------------------------
# Contract 2: serialize_scene with translated_classes filter
# ---------------------------------------------------------------------------

class TestSerializeSceneWithFilter:

    def test_translated_component_is_kept(self):
        """A MonoBehaviour whose class is in translated_classes must appear in output."""
        go = GameObject("Player")
        go.add_component(TranslatedBehaviour)

        result = serialize_scene(translated_classes={"TranslatedBehaviour"})
        go_data = result["game_objects"][0]
        types = [c["type"] for c in go_data["components"]]
        assert "TranslatedBehaviour" in types

    def test_inline_component_is_dropped(self):
        """A MonoBehaviour whose class is NOT in translated_classes must be dropped."""
        go = GameObject("Runner")
        go.add_component(InlineBehaviour)

        result = serialize_scene(translated_classes={"TranslatedBehaviour"})
        go_data = result["game_objects"][0]
        types = [c["type"] for c in go_data["components"]]
        assert "InlineBehaviour" not in types

    def test_gameobject_still_present_after_all_monobehaviours_dropped(self):
        """The contract states: GameObjects are never dropped, only their user components.
        A GO whose only MonoBehaviour is filtered must still appear in game_objects."""
        go = GameObject("InlineOnly")
        go.add_component(InlineBehaviour)

        result = serialize_scene(translated_classes={"TranslatedBehaviour"})
        names = [g["name"] for g in result["game_objects"]]
        assert "InlineOnly" in names

    def test_two_gos_mixed_components_correct_filtering(self):
        """Two GameObjects, one with a translated component and one with only inline.
        After filter: both GOs present, translated component kept, inline dropped."""
        go_a = GameObject("Alpha")
        go_a.add_component(TranslatedBehaviour)

        go_b = GameObject("Beta")
        go_b.add_component(InlineBehaviour)

        result = serialize_scene(translated_classes={"TranslatedBehaviour"})

        # Both GOs must be in the output
        names = {g["name"] for g in result["game_objects"]}
        assert "Alpha" in names
        assert "Beta" in names

        # Alpha's translated component kept
        alpha_data = next(g for g in result["game_objects"] if g["name"] == "Alpha")
        alpha_types = [c["type"] for c in alpha_data["components"]]
        assert "TranslatedBehaviour" in alpha_types

        # Beta's inline component dropped
        beta_data = next(g for g in result["game_objects"] if g["name"] == "Beta")
        beta_types = [c["type"] for c in beta_data["components"]]
        assert "InlineBehaviour" not in beta_types

    def test_engine_primitives_never_dropped_by_filter(self):
        """Transform, SpriteRenderer, etc. must NOT be filtered regardless of
        translated_classes — they are not MonoBehaviours."""
        go = GameObject("Sprite")
        sr = go.add_component(SpriteRenderer)
        sr.asset_ref = "player_sprite"

        # Pass an empty translated_classes set — would drop all MonoBehaviours
        result = serialize_scene(translated_classes=set())
        go_data = result["game_objects"][0]
        types = [c["type"] for c in go_data["components"]]
        assert "SpriteRenderer" in types

    def test_empty_translated_classes_drops_all_monobehaviours(self):
        """An empty set means no MonoBehaviour survives the filter."""
        go = GameObject("Test")
        go.add_component(TranslatedBehaviour)
        go.add_component(InlineBehaviour)

        result = serialize_scene(translated_classes=set())
        go_data = result["game_objects"][0]
        mb_types = [c["type"] for c in go_data["components"]
                    if c.get("is_monobehaviour")]
        assert mb_types == []


# ---------------------------------------------------------------------------
# Contract 3: back-compat — no kwarg means no filtering
# ---------------------------------------------------------------------------

class TestSerializeSceneBackCompat:

    def test_no_kwarg_emits_all_monobehaviours(self):
        """serialize_scene() without translated_classes must emit every MonoBehaviour."""
        go = GameObject("All")
        go.add_component(TranslatedBehaviour)
        go.add_component(InlineBehaviour)

        result = serialize_scene()
        go_data = result["game_objects"][0]
        types = [c["type"] for c in go_data["components"]]
        assert "TranslatedBehaviour" in types
        assert "InlineBehaviour" in types

    def test_none_kwarg_emits_all_monobehaviours(self):
        """serialize_scene(translated_classes=None) must be equivalent to no kwarg."""
        go = GameObject("AllNone")
        go.add_component(TranslatedBehaviour)
        go.add_component(InlineBehaviour)

        result = serialize_scene(translated_classes=None)
        go_data = result["game_objects"][0]
        types = [c["type"] for c in go_data["components"]]
        assert "TranslatedBehaviour" in types
        assert "InlineBehaviour" in types

    def test_back_compat_does_not_raise(self):
        """No exception when calling serialize_scene() without the kwarg on an
        existing scene that was working before FU-1."""
        go = GameObject("Safe")
        go.add_component(TranslatedBehaviour)
        # Must not raise
        result = serialize_scene()
        assert len(result["game_objects"]) == 1


# ---------------------------------------------------------------------------
# Contract 4: gen_coplay runner-to-source-dir derivation rule
# ---------------------------------------------------------------------------

class TestRunnerToSourceDirDerivation:
    """Verify the derivation logic in gen_coplay.main() without actually
    executing the CLI.  We reproduce the derivation rule from the source and
    assert it produces the expected paths for canonical and non-canonical
    runner names.

    The rule (from gen_coplay.py):
        stem = runner_path.stem
        derived = runner_path.parent / (
            stem[4:] + "_python" if stem.startswith("run_") else f"{stem}_python"
        )
    """

    def _derive(self, runner_path: Path) -> Path:
        """Reproduce the derivation logic from gen_coplay.py."""
        stem = runner_path.stem
        return runner_path.parent / (
            stem[4:] + "_python" if stem.startswith("run_") else f"{stem}_python"
        )

    def test_run_game_derives_game_python(self, tmp_path):
        """run_flappy_bird.py → flappy_bird_python/ (strip 'run_' prefix)."""
        runner = tmp_path / "run_flappy_bird.py"
        runner.touch()
        derived = self._derive(runner)
        assert derived.name == "flappy_bird_python"

    def test_run_pacman_derives_pacman_python(self, tmp_path):
        """run_pacman_v2.py → pacman_v2_python/"""
        runner = tmp_path / "run_pacman_v2.py"
        runner.touch()
        derived = self._derive(runner)
        assert derived.name == "pacman_v2_python"

    def test_plain_name_appends_python(self, tmp_path):
        """game.py (no run_ prefix) → game_python/"""
        runner = tmp_path / "game.py"
        runner.touch()
        derived = self._derive(runner)
        assert derived.name == "game_python"

    def test_derived_dir_used_when_exists(self, tmp_path):
        """When the derived directory exists the helper is called; when it
        does not exist the filter is disabled (translated_classes stays None).
        This validates that gen_coplay gates on is_dir() before calling the
        helper."""
        runner = tmp_path / "run_test_game.py"
        runner.touch()
        derived = self._derive(runner)
        # Dir does not exist yet → filter disabled
        assert not derived.is_dir()
        # Create the dir → filter would be enabled
        derived.mkdir()
        assert derived.is_dir()

    def test_derivation_is_sibling_of_runner(self, tmp_path):
        """Derived directory is a sibling of the runner file, not a child."""
        runner = tmp_path / "examples" / "mygame" / "run_mygame.py"
        runner.parent.mkdir(parents=True, exist_ok=True)
        runner.touch()
        derived = self._derive(runner)
        assert derived.parent == runner.parent

    def test_run_prefix_exactly_four_chars_stripped(self, tmp_path):
        """Only the literal 'run_' prefix (4 chars) is stripped."""
        # 'runner_game.py' starts with 'run' but not 'run_' — should append _python
        runner = tmp_path / "runner_game.py"
        runner.touch()
        derived = self._derive(runner)
        # Does NOT start with 'run_', so rule is: stem + '_python'
        assert derived.name == "runner_game_python"
