# PARITY_SCAFFOLD_SKELETON
"""Parity test (SCAFFOLD): UnityEngine.PhysicsMaterial2D.

Documented Unity behavior (https://docs.unity3d.com/ScriptReference/PhysicsMaterial2D.html):
    TODO: fill in canonical Unity behavior summary in 1-3 lines.

Auto-generated by tools/parity_scaffold.py for kind='class'.
Python impl: src.engine.physics.collider.PhysicsMaterial2D

To finish this skeleton:
  1. Read the Unity doc page above and write 1-3 cases below.
  2. Implement scenario_python() against the Python sim.
  3. Implement scenario_csharp_body — code that populates `observables`.
  4. Remove the @pytest.mark.skip and the PARITY_SCAFFOLD_SKELETON marker.
"""
from __future__ import annotations

import pytest

# TODO: import the engine surface — likely `from src.engine.physics.collider import PhysicsMaterial2D`,
#       adjust based on where the symbol actually lives.
from tests.parity._harness import ParityCase, assert_parity


def _py_physicsmaterial2d_class() -> dict:
    """TODO: scenario_python — return a dict of named observables."""
    raise NotImplementedError("parity_scaffold: fill in PhysicsMaterial2D scenario_python")


_CS_PHYSICSMATERIAL2D_CLASS = """
// TODO: scenario_csharp_body — populate `observables` Dictionary<string,object>.
// Reference: https://docs.unity3d.com/ScriptReference/PhysicsMaterial2D.html
throw new System.NotImplementedException("parity_scaffold: fill in PhysicsMaterial2D scenario_csharp");
"""


@pytest.mark.skip(reason="parity-scaffold skeleton: fill in scenario_python and scenario_csharp_body, then remove the SCAFFOLD marker")
def test_physicsmaterial2d_class_parity() -> None:
    assert_parity(
        ParityCase(
            name="PhysicsMaterial2D behavior",
            scenario_python=_py_physicsmaterial2d_class,
            scenario_csharp_body=_CS_PHYSICSMATERIAL2D_CLASS,
        )
    )
