# PARITY_SCAFFOLD_SKELETON
"""Parity test (SCAFFOLD): UnityEngine.Transform.rotation.

Documented Unity behavior (https://docs.unity3d.com/ScriptReference/Transform-rotation.html):
    TODO: fill in canonical Unity behavior summary in 1-3 lines.

Auto-generated by tools/parity_scaffold.py for kind='property'.
Python impl: src.engine.core.Transform.rotation

To finish this skeleton:
  1. Read the Unity doc page above and write 1-3 cases below.
  2. Implement scenario_python() against the Python sim.
  3. Implement scenario_csharp_body — code that populates `observables`.
  4. Remove the @pytest.mark.skip and the PARITY_SCAFFOLD_SKELETON marker.
"""
from __future__ import annotations

import pytest

# TODO: import the engine surface — likely `from src.engine.core import Transform`,
#       adjust based on where the symbol actually lives.
from tests.parity._harness import ParityCase, assert_parity


def _py_transform_rotation() -> dict:
    """TODO: scenario_python — return a dict of named observables."""
    raise NotImplementedError("parity_scaffold: fill in Transform.rotation scenario_python")


_CS_TRANSFORM_ROTATION = """
// TODO: scenario_csharp_body — populate `observables` Dictionary<string,object>.
// Reference: https://docs.unity3d.com/ScriptReference/Transform-rotation.html
throw new System.NotImplementedException("parity_scaffold: fill in Transform.rotation scenario_csharp");
"""


@pytest.mark.skip(reason="parity-scaffold skeleton: fill in scenario_python and scenario_csharp_body, then remove the SCAFFOLD marker")
def test_transform_rotation_parity() -> None:
    assert_parity(
        ParityCase(
            name="Transform.rotation behavior",
            scenario_python=_py_transform_rotation,
            scenario_csharp_body=_CS_TRANSFORM_ROTATION,
        )
    )
