# PARITY_SCAFFOLD_SKELETON
"""Parity test (SCAFFOLD): UnityEngine.GameObject.FindGameObjectsWithTag.

Documented Unity behavior (https://docs.unity3d.com/ScriptReference/GameObject-FindGameObjectsWithTag.html):
    TODO: fill in canonical Unity behavior summary in 1-3 lines.

Auto-generated by tools/parity_scaffold.py for kind='method'.
Python impl: src.engine.core.GameObject.find_game_objects_with_tag

To finish this skeleton:
  1. Read the Unity doc page above and write 1-3 cases below.
  2. Implement scenario_python() against the Python sim.
  3. Implement scenario_csharp_body — code that populates `observables`.
  4. Remove the @pytest.mark.skip and the PARITY_SCAFFOLD_SKELETON marker.
"""
from __future__ import annotations

import pytest

# TODO: import the engine surface — likely `from src.engine.core import GameObject`,
#       adjust based on where the symbol actually lives.
from tests.parity._harness import ParityCase, assert_parity


def _py_gameobject_findgameobjectswithtag() -> dict:
    """TODO: scenario_python — return a dict of named observables."""
    raise NotImplementedError("parity_scaffold: fill in GameObject.FindGameObjectsWithTag scenario_python")


_CS_GAMEOBJECT_FINDGAMEOBJECTSWITHTAG = """
// TODO: scenario_csharp_body — populate `observables` Dictionary<string,object>.
// Reference: https://docs.unity3d.com/ScriptReference/GameObject-FindGameObjectsWithTag.html
throw new System.NotImplementedException("parity_scaffold: fill in GameObject.FindGameObjectsWithTag scenario_csharp");
"""


@pytest.mark.skip(reason="parity-scaffold skeleton: fill in scenario_python and scenario_csharp_body, then remove the SCAFFOLD marker")
def test_gameobject_findgameobjectswithtag_parity() -> None:
    assert_parity(
        ParityCase(
            name="GameObject.FindGameObjectsWithTag behavior",
            scenario_python=_py_gameobject_findgameobjectswithtag,
            scenario_csharp_body=_CS_GAMEOBJECT_FINDGAMEOBJECTSWITHTAG,
        )
    )
