"""Generate parity-test skeletons for untested Unity APIs (M-9 / M-12).

This is the scaffolder both M-9 (bulk backfill) and M-12 (gap-gate auto-skeleton)
share. It walks `data/metrics/parity_matrix.json` for rows where
`has_parity_test == false` and writes a skeleton test file under
`tests/parity/`. Skeletons are marked `# PARITY_SCAFFOLD_SKELETON` at the top so
`src/gates/parity_matrix.py` does NOT count them as real parity tests — only
once an agent removes the marker (after filling in `scenario_python` and
`scenario_csharp_body`) does the API count toward `with_parity_test`.

Two run modes:

    python tools/parity_scaffold.py            # generate skeletons for ALL untested APIs
    python tools/parity_scaffold.py --apis Transform.Translate Transform.Rotate
                                                # generate skeletons for specific APIs

Existing files are NOT overwritten unless `--force` is given. The catalog tries
to avoid surprises when an agent has already started filling in a skeleton.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PARITY_DIR = REPO_ROOT / "tests" / "parity"
MATRIX_JSON = REPO_ROOT / "data" / "metrics" / "parity_matrix.json"

SCAFFOLD_MARKER = "# PARITY_SCAFFOLD_SKELETON"


# APIs that are intentionally NOT parity-testable in headless mode and should
# be parked rather than skeletoned. The skeleton tool writes a tiny "park
# notice" file for each so the parity matrix can reflect that the API is
# documented as out-of-scope rather than untested.
PARKED_APIS: dict[str, str] = {
    "AudioSource": "Audio playback requires Unity's audio engine; no headless equivalent.",
    "AudioClip": "Audio data type, only meaningful when AudioSource plays it.",
    "AudioListener": "Audio capture; depends on AudioSource which is parked.",
    "Canvas": "UI rendering tree depends on Unity Editor's UI system.",
    "RectTransform": "UI-specific Transform; depends on Canvas which is parked.",
    "Text": "UI Text component requires UnityEngine.UI; rendering depends on Canvas.",
    "Image": "UI Image component; depends on Canvas which is parked.",
    "Button": "UI Button component; depends on Canvas + EventSystem which are parked.",
    "SceneManager": "Scene loading is environment-bound; not meaningfully testable headless.",
    "DOTween (Tween)": "Third-party tweening library; out of unity-py-sim's surface.",
}


def _load_untested_rows() -> list[dict]:
    matrix = json.loads(MATRIX_JSON.read_text(encoding="utf-8"))
    return [r for r in matrix["rows"] if not r.get("has_parity_test")]


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "_", s.lower()).strip("_")


def _skeleton_filename(unity_class: str, unity_member: str) -> str:
    cls = _slug(unity_class)
    if unity_member:
        return f"test_{cls}_{_slug(unity_member)}_parity.py"
    return f"test_{cls}_class_parity.py"


def _skeleton_text(row: dict) -> str:
    cls = row["unity_class"]
    member = row["unity_member"] or ""
    kind = row["kind"]
    py_module = row.get("python_module") or "src.engine.core"
    py_class = row.get("python_class") or cls
    docs_path = (
        f"https://docs.unity3d.com/ScriptReference/{cls}-{member}.html"
        if member else f"https://docs.unity3d.com/ScriptReference/{cls}.html"
    )
    api = f"{cls}.{member}" if member else cls

    func_slug = _slug(f"{cls}_{member or 'class'}")
    cs_const = f"_CS_{func_slug.upper()}"

    lines = [
        SCAFFOLD_MARKER,
        f'"""Parity test (SCAFFOLD): UnityEngine.{api}.',
        "",
        f"Documented Unity behavior ({docs_path}):",
        "    TODO: fill in canonical Unity behavior summary in 1-3 lines.",
        "",
        f"Auto-generated by tools/parity_scaffold.py for kind={kind!r}.",
        f"Python impl: {py_module}.{py_class}" + (f".{row['python_member']}" if row.get('python_member') else ""),
        "",
        "To finish this skeleton:",
        "  1. Read the Unity doc page above and write 1-3 cases below.",
        "  2. Implement scenario_python() against the Python sim.",
        "  3. Implement scenario_csharp_body — code that populates `observables`.",
        "  4. Remove the @pytest.mark.skip and the PARITY_SCAFFOLD_SKELETON marker.",
        '"""',
        "from __future__ import annotations",
        "",
        "import pytest",
        "",
        f"# TODO: import the engine surface — likely `from {py_module} import {py_class}`,",
        "#       adjust based on where the symbol actually lives.",
        "from tests.parity._harness import ParityCase, assert_parity",
        "",
        "",
        f"def _py_{func_slug}() -> dict:",
        '    """TODO: scenario_python — return a dict of named observables."""',
        f'    raise NotImplementedError("parity_scaffold: fill in {api} scenario_python")',
        "",
        "",
        f'{cs_const} = """',
        "// TODO: scenario_csharp_body — populate `observables` Dictionary<string,object>.",
        f"// Reference: {docs_path}",
        f'throw new System.NotImplementedException("parity_scaffold: fill in {api} scenario_csharp");',
        '"""',
        "",
        "",
        '@pytest.mark.skip(reason="parity-scaffold skeleton: fill in scenario_python and scenario_csharp_body, then remove the SCAFFOLD marker")',
        f"def test_{func_slug}_parity() -> None:",
        "    assert_parity(",
        "        ParityCase(",
        f'            name="{api} behavior",',
        f"            scenario_python=_py_{func_slug},",
        f"            scenario_csharp_body={cs_const},",
        "        )",
        "    )",
        "",
    ]
    return "\n".join(lines)


def _park_text(unity_class: str, reason: str) -> str:
    """Tiny marker file that documents why the API is out-of-scope. Picked up
    by the parity matrix as 'parity_skipped' once we wire that branch in."""
    return (
        f"# PARITY_SCAFFOLD_PARKED\n"
        f'"""Parked: UnityEngine.{unity_class} is intentionally NOT parity-tested.\n\n'
        f"Reason: {reason}\n\n"
        "If a future game depends on this surface, promote this file to a real\n"
        "parity test by removing the PARITY_SCAFFOLD_PARKED marker and wiring up\n"
        f"a ParityCase. Until then, this row counts as 'parity_skipped' rather\n"
        "than 'untested' in data/metrics/parity_matrix.json.\n"
        '"""\n'
    )


def _filter_apis(rows: list[dict], allow: list[str]) -> list[dict]:
    if not allow:
        return rows
    allowed = set()
    for spec in allow:
        if "." in spec:
            cls, member = spec.split(".", 1)
            allowed.add((cls, member))
        else:
            allowed.add((spec, ""))
    return [r for r in rows if (r["unity_class"], r["unity_member"] or "") in allowed]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate parity-test skeletons.")
    parser.add_argument(
        "--apis", nargs="+", default=[],
        help="Only scaffold these APIs (e.g. 'Transform.Translate'). Class-only specs ('Transform') match the class row.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite existing skeleton/parked files.")
    parser.add_argument("--park-untestable", action="store_true",
                        help="Also write parked notices for the curated untestable list (Audio, UI, etc.).")
    args = parser.parse_args(argv)

    rows = _load_untested_rows()
    rows = _filter_apis(rows, args.apis)

    written = 0
    skipped = 0
    for row in rows:
        cls = row["unity_class"]
        member = row["unity_member"] or ""
        is_parked = args.park_untestable and not member and cls in PARKED_APIS

        if is_parked:
            target = PARITY_DIR / f"test_{_slug(cls)}_parked.py"
            content = _park_text(cls, PARKED_APIS[cls])
        else:
            target = PARITY_DIR / _skeleton_filename(cls, member)
            content = _skeleton_text(row)

        if target.exists() and not args.force:
            skipped += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written += 1

    print(f"parity_scaffold: wrote {written}, skipped {skipped} (already exist; use --force to overwrite)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
