"""Render data/metrics/history/*.json snapshots into data/metrics/dashboard.md.

Reads every JSON snapshot in chronological order (lexicographic sort works
because filenames use UTC ISO timestamps) and writes a markdown dashboard
with: latest summary, recent-trend table, per-game accuracy, test inventory.

Pure presentation — adds no metrics that aren't already in the snapshot
files. New columns require a corresponding `src/gates/snapshot.py` field.

Usage:
    python tools/render_dashboard.py
    python tools/render_dashboard.py --last-n 20
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
METRICS_DIR = ROOT / "data" / "metrics"
HISTORY_DIR = METRICS_DIR / "history"
DASHBOARD_PATH = METRICS_DIR / "dashboard.md"


def _load_history(history_dir: Path) -> list[dict[str, Any]]:
    if not history_dir.exists():
        return []
    snapshots: list[dict[str, Any]] = []
    for p in sorted(history_dir.glob("*.json")):
        try:
            data = json.loads(p.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(data, dict):
            snapshots.append(data)
    return snapshots


def _fmt_pct(v: Any) -> str:
    if not isinstance(v, (int, float)):
        return "—"
    pct = v * 100 if v <= 1 else v
    return f"{pct:.1f}%"


def _fmt_num(v: Any, decimals: int = 3) -> str:
    if not isinstance(v, (int, float)):
        return "—"
    return f"{v:.{decimals}f}"


def _arrow(prev: Any, cur: Any) -> str:
    if not isinstance(prev, (int, float)) or not isinstance(cur, (int, float)):
        return ""
    if abs(cur - prev) < 1e-6:
        return "→"
    return "↑" if cur > prev else "↓"


def render_dashboard(
    history_dir: Path = HISTORY_DIR,
    output_path: Path = DASHBOARD_PATH,
    last_n: int = 10,
) -> str:
    snapshots = _load_history(history_dir)
    if not snapshots:
        md = (
            "# Translation Accuracy Dashboard\n\n"
            "_No snapshots yet._ Run `python -m src.gates.snapshot` to record one.\n"
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(md)
        return md

    latest = snapshots[-1]
    recent = snapshots[-last_n:]

    lines: list[str] = []
    lines.append("# Translation Accuracy Dashboard")
    lines.append("")
    lines.append(
        f"_Auto-generated by `tools/render_dashboard.py`. "
        f"{len(snapshots)} snapshot(s) tracked._"
    )
    lines.append("")

    lines.append("## Latest Snapshot")
    lines.append("")
    lines.append(f"- **Timestamp**: `{latest.get('timestamp', '—')}`")
    if latest.get("git_commit"):
        lines.append(f"- **Commit**: `{latest['git_commit']}`")
    if latest.get("git_branch"):
        lines.append(f"- **Branch**: `{latest['git_branch']}`")
    if latest.get("notes"):
        lines.append(f"- **Notes**: {latest['notes']}")
    lines.append("")

    m = latest.get("metrics", {}) or {}
    prev_m = (snapshots[-2].get("metrics", {}) if len(snapshots) > 1 else {}) or {}
    rows = [
        ("Corpus compile (dotnet build)", "corpus_compile_pct", _fmt_pct),
        ("Avg overall accuracy", "avg_overall", _fmt_num),
        ("Avg class match", "avg_class", _fmt_num),
        ("Avg method match", "avg_method", _fmt_num),
        ("Avg field match", "avg_field", _fmt_num),
        ("Avg using match", "avg_using", _fmt_num),
        ("Roundtrip compile %", "roundtrip_compile_pct", _fmt_pct),
        ("Roundtrip AST %", "roundtrip_ast_pct", _fmt_pct),
        ("Unity API surface (static)", "parity_implemented_pct", _fmt_pct),
        ("Unity API parity (tested)", "parity_test_pct", _fmt_pct),
        ("Parity tests passing — dotnet (ASP-4 ≥80%)", "parity_dotnet_pct", _fmt_pct),
        ("Parity tests passing — CoPlay (ASP-4 ≥70%)", "parity_coplay_pct", _fmt_pct),
    ]
    lines.append("| Metric | Value | Δ |")
    lines.append("|---|---|---|")
    for label, key, formatter in rows:
        lines.append(f"| {label} | {formatter(m.get(key))} | {_arrow(prev_m.get(key), m.get(key))} |")
    lines.append("")

    lines.append(f"## Trend (last {len(recent)} snapshots)")
    lines.append("")
    lines.append(
        "| Time | Compile | Avg | Class | Method | Field | RT Compile | RT AST | "
        "API Surface | Parity Test |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for snap in recent:
        sm = snap.get("metrics", {}) or {}
        ts = str(snap.get("timestamp", ""))[:19]
        lines.append(
            f"| `{ts}` | "
            f"{_fmt_pct(sm.get('corpus_compile_pct'))} | "
            f"{_fmt_num(sm.get('avg_overall'))} | "
            f"{_fmt_num(sm.get('avg_class'))} | "
            f"{_fmt_num(sm.get('avg_method'))} | "
            f"{_fmt_num(sm.get('avg_field'))} | "
            f"{_fmt_pct(sm.get('roundtrip_compile_pct'))} | "
            f"{_fmt_pct(sm.get('roundtrip_ast_pct'))} | "
            f"{_fmt_pct(sm.get('parity_implemented_pct'))} | "
            f"{_fmt_pct(sm.get('parity_test_pct'))} |"
        )
    lines.append("")

    bg = latest.get("by_game", {}) or {}
    if bg:
        lines.append("## Per-Game Accuracy (latest)")
        lines.append("")
        lines.append("| Game | Pairs | Avg Overall | Class | Method | Field |")
        lines.append("|---|---|---|---|---|---|")
        for game, stats in sorted(bg.items()):
            stats = stats or {}
            lines.append(
                f"| {game} | {stats.get('count', '—')} | "
                f"{_fmt_num(stats.get('avg_overall'))} | "
                f"{_fmt_num(stats.get('avg_class'))} | "
                f"{_fmt_num(stats.get('avg_method'))} | "
                f"{_fmt_num(stats.get('avg_field'))} |"
            )
        lines.append("")

    tc = latest.get("test_counts", {}) or {}
    if tc:
        lines.append("## Test Inventory (latest)")
        lines.append("")
        lines.append("| Suite | Files |")
        lines.append("|---|---|")
        for suite, count in tc.items():
            lines.append(f"| {suite} | {count} |")
        lines.append("")

    md = "\n".join(lines) + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(md)
    return md


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--history-dir", default=str(HISTORY_DIR))
    p.add_argument("--output", default=str(DASHBOARD_PATH))
    p.add_argument("--last-n", type=int, default=10)
    args = p.parse_args(argv)
    md = render_dashboard(
        history_dir=Path(args.history_dir),
        output_path=Path(args.output),
        last_n=args.last_n,
    )
    print(f"[dashboard] wrote {args.output} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
