"""Render data/metrics/parity_matrix.json into data/metrics/parity_matrix.md.

Reads the matrix produced by `python -m src.gates.parity_matrix` and
emits a markdown report with: aggregate counts, per-kind breakdown,
per-Unity-class breakdown, and a per-row checklist (✓/—).

Pure presentation — adds no metrics that aren't already in the matrix.

Usage:
    python tools/render_parity_matrix.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
MATRIX_PATH = ROOT / "data" / "metrics" / "parity_matrix.json"
OUTPUT_PATH = ROOT / "data" / "metrics" / "parity_matrix.md"


def _check(b: bool) -> str:
    return "✅" if b else "—"


def _pct(num: int, denom: int) -> str:
    if denom == 0:
        return "—"
    return f"{num}/{denom} ({100 * num / denom:.1f}%)"


def render(matrix: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("# Engine ↔ Unity API Parity Matrix")
    lines.append("")
    lines.append(
        "_Auto-generated by `tools/render_parity_matrix.py` from "
        "`data/metrics/parity_matrix.json`. Source of truth for the "
        "API parity claim in CLAUDE.md._"
    )
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    total = matrix.get("total_apis", 0)
    impl = matrix.get("implemented", 0)
    tests = matrix.get("with_parity_test", 0)
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Total claimed APIs | {total} |")
    lines.append(f"| Implementation coverage | {_pct(impl, total)} |")
    lines.append(f"| Parity-test coverage | {_pct(tests, total)} |")
    lines.append("")

    by_kind = matrix.get("by_kind", {})
    if by_kind:
        lines.append("## By Kind")
        lines.append("")
        lines.append("| Kind | Implementation | Parity Tests |")
        lines.append("|---|---|---|")
        for kind in ("class", "method", "property", "lifecycle", "enum", "pattern"):
            stats = by_kind.get(kind)
            if not stats:
                continue
            t = stats["total"]
            i = stats["implemented"]
            tc = stats["with_parity_test"]
            lines.append(f"| {kind} | {_pct(i, t)} | {_pct(tc, t)} |")
        lines.append("")

    by_class = matrix.get("by_unity_class", {})
    if by_class:
        lines.append("## By Unity Class")
        lines.append("")
        lines.append("| Class | Members | Implemented | Parity-tested |")
        lines.append("|---|---|---|---|")
        for cls in sorted(by_class):
            stats = by_class[cls]
            t = stats["total"]
            i = stats["implemented"]
            tc = stats["with_parity_test"]
            lines.append(f"| `{cls}` | {t} | {_pct(i, t)} | {_pct(tc, t)} |")
        lines.append("")

    rows = matrix.get("rows", [])
    if rows:
        lines.append("## Detailed Rows")
        lines.append("")
        lines.append("| Class | Member | Kind | Implementation | Parity Test |")
        lines.append("|---|---|---|---|---|")
        # Sort: class A-Z, then member A-Z, with whole-class rows first
        sorted_rows = sorted(
            rows,
            key=lambda r: (r["unity_class"], r["unity_member"] or ""),
        )
        for r in sorted_rows:
            member = r["unity_member"] or "_(class)_"
            lines.append(
                f"| `{r['unity_class']}` | `{member}` | {r['kind']} | "
                f"{_check(r['has_python_impl'])} | {_check(r['has_parity_test'])} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--matrix", default=str(MATRIX_PATH))
    p.add_argument("--output", default=str(OUTPUT_PATH))
    args = p.parse_args(argv)

    matrix_path = Path(args.matrix)
    if not matrix_path.exists():
        print(
            f"[parity] {matrix_path} not found — "
            f"run `python -m src.gates.parity_matrix` first."
        )
        return 1

    matrix = json.loads(matrix_path.read_text())
    md = render(matrix)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md)
    print(f"[parity] wrote {out} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
